# stage 1
FROM node:16 as node
WORKDIR /app
COPY . .
RUN npm install
RUN set  NODE_OPTIONS=--openssl-legacy-provider
RUN node -v
RUN npm run build --prod

# stage 2
FROM nginx:alpine
COPY --from=node /app/dist/MaterialAdminTheme /usr/share/nginx/html